apns-php: ApnsPHP_Message Class Reference
ApnsPHP_Message Class Reference
Message
The Push Notification Message.
Public Member Functions
void __construct (string $sDeviceToken=null)
Constructor.
string __toString ()
PHP Magic Method.
void addRecipient (string $sDeviceToken)
Add a recipient device token.
boolean getAutoAdjustLongPayload ()
Get the auto-adjust long payload value.
integer getBadge ()
Get the number to badge the application icon with.
string getCategory ()
Get the category of notification.
boolean getContentAvailable ()
Get if should initiates the Newsstand background download.
mixed getCustomIdentifier ()
Get the custom message identifier.
string getCustomProperty (string $sName)
Get the custom property value.
string getCustomPropertyName ()
Get the first custom property name.
array getCustomPropertyNames ()
Get all custom properties names.
mixed getCustomPropertyValue ()
Get the first custom property value.
integer getExpiry ()
Get the expiry value.
string getPayload ()
Convert the message in a JSON-encoded payload.
string getRecipient (integer $nRecipient=0)
Get a recipient.
array getRecipients ()
Get all recipients.
integer getRecipientsNumber ()
Get the number of recipients.
string getSound ()
Get the sound to play.
string getText ()
Get the alert message to display to the user.
void setAutoAdjustLongPayload (boolean $bAutoAdjust)
Set the auto-adjust long payload value.
void setBadge (integer $nBadge)
Set the number to badge the application icon with.
void setCategory (string $sCategory= '')
Set the category of notification.
void setContentAvailable (boolean $bContentAvailable=true)
Initiates the Newsstand background download.
void setCustomIdentifier (mixed $mCustomIdentifier)
Set the custom message identifier.
void setCustomProperty (string $sName, mixed $mValue)
Set a custom property.
void setExpiry (integer $nExpiryValue)
Set the expiry value.
void setSound (string $sSound= 'default')
Set the sound to play.
void setText (string $sText)
Set the alert message to display to the user.
Data Fields
const APPLE_RESERVED_NAMESPACE = 'aps'
string The Apple-reserved aps namespace.
const PAYLOAD_MAXIMUM_SIZE = 2048
integer The maximum size allowed for a notification payload.
Protected Member Functions
array _getPayload ()
Get the payload dictionary.
Protected Attributes
mixed $_aCustomProperties
Custom properties container.
array $_aDeviceTokens = array()
Recipients device tokens.
boolean $_bAutoAdjustLongPayload = true
If the JSON payload is longer than maximum allowed size, shorts message text.
boolean $_bContentAvailable
True to initiates the Newsstand background download.
mixed $_mCustomIdentifier
Custom message identifier.
integer $_nBadge
Number to badge the application icon with.
integer $_nExpiryValue = 604800
That message will expire in 604800 seconds (86400 * 7, 7 days) if not successful delivered.
string $_sCategory
notification category.
string $_sSound
Sound to play.
string $_sText
Alert message to display to the user.
Detailed Description
The Push Notification Message.
The class represents a message to be delivered to an end user device. Notification Service.
See Also
http://tinyurl.com/ApplePushNotificationPayload
Definition at line 34 of file Message.php.
Constructor & Destructor Documentation
void __construct (string $sDeviceToken = null)
Constructor.
Parameters
$sDeviceToken [optional] Recipients device token.
Definition at line 60 of file Message.php.
References addRecipient().
     {
         if (isset($sDeviceToken)) {
             $this->addRecipient($sDeviceToken);
         }
     }
Member Function Documentation
string __toString ()
PHP Magic Method.
When an object is "converted" to a string, JSON-encoded payload is returned.
Returns
JSON-encoded payload.
Definition at line 346 of file Message.php.
References getPayload().
     {
         try {
             $sJSONPayload = $this->getPayload();
         } catch (ApnsPHP_Message_Exception $e) {
             $sJSONPayload = '';
         }
         return $sJSONPayload;
     }
array _getPayload () protected
Get the payload dictionary.
Returns
The payload dictionary.
Definition at line 361 of file Message.php.
Referenced by getPayload().
     {
         $aPayload[self::APPLE_RESERVED_NAMESPACE] = array();
         if (isset($this->_sText)) {
             $aPayload[self::APPLE_RESERVED_NAMESPACE]['alert'] = (string)$this->_sText;
         }
         if (isset($this->_nBadge) && $this->_nBadge >= 0) {
             $aPayload[self::APPLE_RESERVED_NAMESPACE]['badge'] = (int)$this->_nBadge;
         }
         if (isset($this->_sSound)) {
             $aPayload[self::APPLE_RESERVED_NAMESPACE]['sound'] = (string)$this->_sSound;
         }
         if (isset($this->_bContentAvailable)) {
             $aPayload[self::APPLE_RESERVED_NAMESPACE]['content-available'] = (int)$this->_bContentAvailable;
         }
         if (isset($this->_sCategory)) {
             $aPayload[self::APPLE_RESERVED_NAMESPACE]['category'] = (string)$this->_sCategory;
         }
         if (is_array($this->_aCustomProperties)) {
             foreach($this->_aCustomProperties as $sPropertyName => $mPropertyValue) {
                 $aPayload[$sPropertyName] = $mPropertyValue;
             }
         }
         return $aPayload;
     }
void addRecipient (string $sDeviceToken)
Add a recipient device token.
Parameters
$sDeviceToken Recipients device token.
Exceptions
ApnsPHP_Message_Exception if the device token is not well formed.
Definition at line 74 of file Message.php.
Referenced by __construct().
     {
         if (!preg_match('~^[a-f0-9]{64}$~i', $sDeviceToken)) {
             throw new ApnsPHP_Message_Exception(
                 "Invalid device token '{$sDeviceToken}'"
             );
         }
         $this->_aDeviceTokens[] = $sDeviceToken;
     }
boolean getAutoAdjustLongPayload ()
Get the auto-adjust long payload value.
Returns
The auto-adjust long payload value.
Definition at line 335 of file Message.php.
References $_bAutoAdjustLongPayload.
     {
         return $this->_bAutoAdjustLongPayload;
     }
integer getBadge ()
Get the number to badge the application icon with.
Returns
The number to badge the application icon with.
Definition at line 164 of file Message.php.
References $_nBadge.
     {
         return $this->_nBadge;
     }
string getCategory ()
Get the category of notification.
Returns
The notification category
Definition at line 205 of file Message.php.
References $_sCategory.
     {
         return $this->_sCategory;
     }
boolean getContentAvailable ()
Get if should initiates the Newsstand background download.
Returns
Initiates the Newsstand background download property.
Definition at line 233 of file Message.php.
References $_bContentAvailable.
     {
         return $this->_bContentAvailable;
     }
mixed getCustomIdentifier ()
Get the custom message identifier.
Returns
The custom message identifier.
Definition at line 485 of file Message.php.
References $_mCustomIdentifier.
     {
         return $this->_mCustomIdentifier;
     }
string getCustomProperty (string $sName)
Get the custom property value.
Parameters
$sName Custom property name.
Exceptions
ApnsPHP_Message_Exception if no property exists with the specified name.
Returns
The custom property value.
Definition at line 309 of file Message.php.
     {
         if (!array_key_exists($sName, $this->_aCustomProperties)) {
             throw new ApnsPHP_Message_Exception(
                 "No property exists with the specified name '{$sName}'."
             );
         }
         return $this->_aCustomProperties[$sName];
     }
string getCustomPropertyName ()
Get the first custom property name.
Deprecated:
Use getCustomPropertyNames() instead.
Returns
The first custom property name.
Definition at line 263 of file Message.php.
     {
         if (!is_array($this->_aCustomProperties)) {
             return;
         }
         $aKeys = array_keys($this->_aCustomProperties);
         return $aKeys[0];
     }
array getCustomPropertyNames ()
Get all custom properties names.
Returns
All properties names.
Definition at line 293 of file Message.php.
     {
         if (!is_array($this->_aCustomProperties)) {
             return array();
         }
         return array_keys($this->_aCustomProperties);
     }
mixed getCustomPropertyValue ()
Get the first custom property value.
Deprecated:
Use getCustomProperty() instead.
Returns
The first custom property value.
Definition at line 279 of file Message.php.
     {
         if (!is_array($this->_aCustomProperties)) {
             return;
         }
         $aKeys = array_keys($this->_aCustomProperties);
         return $this->_aCustomProperties[$aKeys[0]];
     }
integer getExpiry ()
Get the expiry value.
Returns
The expire message value (in seconds).
Definition at line 458 of file Message.php.
References $_nExpiryValue.
Referenced by ApnsPHP_Push\add().
     {
         return $this->_nExpiryValue;
     }
string getPayload ()
Convert the message in a JSON-encoded payload.
Exceptions
ApnsPHP_Message_Exception if payload is longer than maximum allowed size and AutoAdjustLongPayload is disabled.
Returns
JSON-encoded payload.
Definition at line 397 of file Message.php.
References _getPayload().
Referenced by __toString(), and ApnsPHP_Push\add().
     {
         $sJSON = json_encode($this->_getPayload(), defined('JSON_UNESCAPED_UNICODE') ? JSON_UNESCAPED_UNICODE : 0);
         if (!defined('JSON_UNESCAPED_UNICODE') && function_exists('mb_convert_encoding')) {
             $sJSON = preg_replace_callback(
                 '~\\\\u([0-9a-f]{4})~i',
                 create_function('$aMatches', 'return mb_convert_encoding(pack("H*", $aMatches[1]), "UTF-8", "UTF-16");'),
                 $sJSON);
         }
         $sJSONPayload = str_replace(
             '"' . self::APPLE_RESERVED_NAMESPACE . '":[]',
             '"' . self::APPLE_RESERVED_NAMESPACE . '":{}',
             $sJSON
         );
         $nJSONPayloadLen = strlen($sJSONPayload);
         if ($nJSONPayloadLen > self::PAYLOAD_MAXIMUM_SIZE) {
             if ($this->_bAutoAdjustLongPayload) {
                 $nMaxTextLen = $nTextLen = strlen($this->_sText) - ($nJSONPayloadLen - self::PAYLOAD_MAXIMUM_SIZE);
                 if ($nMaxTextLen > 0) {
                     while (strlen($this->_sText = mb_substr($this->_sText, 0, --$nTextLen, 'UTF-8')) > $nMaxTextLen);
                     return $this->getPayload();
                 } else {
                     throw new ApnsPHP_Message_Exception(
                         "JSON Payload is too long: {$nJSONPayloadLen} bytes. Maximum size is " .
                         self::PAYLOAD_MAXIMUM_SIZE . " bytes. The message text can not be auto-adjusted."
                     );
                 }
             } else {
                 throw new ApnsPHP_Message_Exception(
                     "JSON Payload is too long: {$nJSONPayloadLen} bytes. Maximum size is " .
                     self::PAYLOAD_MAXIMUM_SIZE . " bytes"
                 );
             }
         }
         return $sJSONPayload;
     }
string getRecipient (integer $nRecipient = 0)
Get a recipient.
Parameters
$nRecipient [optional] Recipient number to return.
Exceptions
ApnsPHP_Message_Exception if no recipient number exists.
Returns
The recipient token at index $nRecipient.
Definition at line 92 of file Message.php.
Referenced by ApnsPHP_Push\add().
     {
         if (!isset($this->_aDeviceTokens[$nRecipient])) {
             throw new ApnsPHP_Message_Exception(
                 "No recipient at index '{$nRecipient}'"
             );
         }
         return $this->_aDeviceTokens[$nRecipient];
     }
array getRecipients ()
Get all recipients.
Returns
Array of all recipients device token.
Definition at line 117 of file Message.php.
References $_aDeviceTokens.
     {
         return $this->_aDeviceTokens;
     }
integer getRecipientsNumber ()
Get the number of recipients.
Returns
Recipient's number.
Definition at line 107 of file Message.php.
Referenced by ApnsPHP_Push\add().
     {
         return count($this->_aDeviceTokens);
     }
string getSound ()
Get the sound to play.
Returns
The sound to play.
Definition at line 185 of file Message.php.
References $_sSound.
     {
         return $this->_sSound;
     }
string getText ()
Get the alert message to display to the user.
Returns
The alert message to display to the user.
Definition at line 137 of file Message.php.
References $_sText.
     {
         return $this->_sText;
     }
void setAutoAdjustLongPayload (boolean $bAutoAdjust)
Set the auto-adjust long payload value.
Parameters
$bAutoAdjust If true a long payload is shorted cutting long text value.
Definition at line 325 of file Message.php.
     {
         $this->_bAutoAdjustLongPayload = (boolean)$bAutoAdjust;
     }
void setBadge (integer $nBadge)
Set the number to badge the application icon with.
Parameters
$nBadge A number to badge the application icon with.
Exceptions
ApnsPHP_Message_Exception if badge is not an integer.
Definition at line 149 of file Message.php.
     {
         if (!is_int($nBadge)) {
             throw new ApnsPHP_Message_Exception(
                 "Invalid badge number '{$nBadge}'"
             );
         }
         $this->_nBadge = $nBadge;
     }
void setCategory (string $sCategory = '')
Set the category of notification.
Parameters
$sCategory [optional] A category for ios8 notification actions.
Definition at line 195 of file Message.php.
     {
         $this->_sCategory = $sCategory;
     }
void setContentAvailable (boolean $bContentAvailable = true)
Initiates the Newsstand background download.
See Also
http://tinyurl.com/ApplePushNotificationNewsstand
Parameters
$bContentAvailable True to initiates the Newsstand background download.
Exceptions
ApnsPHP_Message_Exception if ContentAvailable is not a boolean.
Definition at line 218 of file Message.php.
     {
         if (!is_bool($bContentAvailable)) {
             throw new ApnsPHP_Message_Exception(
                 "Invalid content-available value '{$bContentAvailable}'"
             );
         }
         $this->_bContentAvailable = $bContentAvailable ? true : null;
     }
void setCustomIdentifier (mixed $mCustomIdentifier)
Set the custom message identifier.
The custom message identifier is useful to associate a push notification to a DB record or an User entry for example. The custom message identifier can be retrieved in case of error using the getCustomIdentifier() method of an entry retrieved by the getErrors() method. This custom identifier, if present, is also used in all status message by the ApnsPHP_Push class.
Parameters
$mCustomIdentifier The custom message identifier.
Definition at line 475 of file Message.php.
     {
         $this->_mCustomIdentifier = $mCustomIdentifier;
     }
void setCustomProperty (string $sName, mixed $mValue)
Set a custom property.
Parameters
$sName Custom property name.
$mValue Custom property value.
Exceptions
ApnsPHP_Message_Exception if custom property name is not outside the Apple-reserved 'aps' namespace.
Definition at line 246 of file Message.php.
     {
         if (trim($sName) == self::APPLE_RESERVED_NAMESPACE) {
             throw new ApnsPHP_Message_Exception(
                 "Property name '" . self::APPLE_RESERVED_NAMESPACE . "' can not be used for custom property."
             );
         }
         $this->_aCustomProperties[trim($sName)] = $mValue;
     }
void setExpiry (integer $nExpiryValue)
Set the expiry value.
Parameters
$nExpiryValue This message will expire in N seconds if not successful delivered.
Definition at line 443 of file Message.php.
     {
         if (!is_int($nExpiryValue)) {
             throw new ApnsPHP_Message_Exception(
                 "Invalid seconds number '{$nExpiryValue}'"
             );
         }
         $this->_nExpiryValue = $nExpiryValue;
     }
void setSound (string $sSound = 'default')
Set the sound to play.
Parameters
$sSound [optional] A sound to play ('default sound' is the default sound).
Definition at line 175 of file Message.php.
     {
         $this->_sSound = $sSound;
     }
void setText (string $sText)
Set the alert message to display to the user.
Parameters
$sText An alert message to display to the user.
Definition at line 127 of file Message.php.
     {
         $this->_sText = $sText;
     }
Field Documentation
mixed $_aCustomProperties protected
Custom properties container.
Definition at line 49 of file Message.php.
array $_aDeviceTokens = array() protected
Recipients device tokens.
Definition at line 41 of file Message.php.
Referenced by getRecipients().
boolean $_bAutoAdjustLongPayload = true protected
If the JSON payload is longer than maximum allowed size, shorts message text.
Definition at line 39 of file Message.php.
Referenced by getAutoAdjustLongPayload().
boolean $_bContentAvailable protected
True to initiates the Newsstand background download.
See Also
http://tinyurl.com/ApplePushNotificationNewsstand
Definition at line 47 of file Message.php.
Referenced by getContentAvailable().
mixed $_mCustomIdentifier protected
Custom message identifier.
Definition at line 53 of file Message.php.
Referenced by getCustomIdentifier().
integer $_nBadge protected
Number to badge the application icon with.
Definition at line 44 of file Message.php.
Referenced by getBadge().
integer $_nExpiryValue = 604800 protected
That message will expire in 604800 seconds (86400 * 7, 7 days) if not successful delivered.
Definition at line 51 of file Message.php.
Referenced by getExpiry().
string $_sCategory protected
notification category.
Definition at line 46 of file Message.php.
Referenced by getCategory().
string $_sSound protected
Sound to play.
Definition at line 45 of file Message.php.
Referenced by getSound().
string $_sText protected
Alert message to display to the user.
Definition at line 43 of file Message.php.
Referenced by getText().
const APPLE_RESERVED_NAMESPACE = 'aps'
string The Apple-reserved aps namespace.
Definition at line 37 of file Message.php.
const PAYLOAD_MAXIMUM_SIZE = 2048
integer The maximum size allowed for a notification payload.
Definition at line 36 of file Message.php.
The documentation for this class was generated from the following file:
Message.php