apns-php: ApnsPHP_Abstract Class Reference
ApnsPHP_Abstract Class Reference
ApnsPHP
Abstract class: this is the superclass for all Apple Push Notification Service classes.
Public Member Functions
void __construct (integer $nEnvironment, string $sProviderCertificateFile)
Constructor.
void connect ()
Connects to Apple Push Notification service server.
boolean disconnect ()
Disconnects from Apple Push Notifications service server.
string getCertificateAuthority ()
Get the Root Certification Authority file path.
integer getConnectRetryInterval ()
Get the connect retry interval.
integer getConnectRetryTimes ()
Get the connect retry time value.
integer getConnectTimeout ()
Get the connection timeout.
ApnsPHP_Log_Interface getLogger ()
Get the Logger instance.
integer getSocketSelectTimeout ()
Get the TCP socket select timeout.
integer getWriteInterval ()
Get the write interval.
void setConnectRetryInterval (integer $nRetryInterval)
Set the connect retry interval.
void setConnectRetryTimes (integer $nRetryTimes)
Set the connect retry times value.
void setConnectTimeout (integer $nTimeout)
Set the connection timeout.
void setLogger (ApnsPHP_Log_Interface $logger)
Set the Logger instance to use for logging purpose.
void setProviderCertificatePassphrase (string $sProviderCertificatePassphrase)
Set the Provider Certificate passphrase.
void setRootCertificationAuthority (string $sRootCertificationAuthorityFile)
Set the Root Certification Authority file.
void setSocketSelectTimeout (integer $nSelectTimeout)
Set the TCP socket select timeout.
void setWriteInterval (integer $nWriteInterval)
Set the write interval.
Data Fields
const CONNECT_RETRY_INTERVAL = 1000000
integer Default connect retry interval in micro seconds.
const DEVICE_BINARY_SIZE = 32
integer Device token length.
const ENVIRONMENT_PRODUCTION = 0
integer Production environment.
const ENVIRONMENT_SANDBOX = 1
integer Sandbox environment.
const SOCKET_SELECT_TIMEOUT = 1000000
integer Default socket select timeout in micro seconds.
const WRITE_INTERVAL = 10000
integer Default write interval in micro seconds.
Protected Member Functions
boolean _connect ()
Connects to Apple Push Notification service server.
void _log (string $sMessage)
Logs a message through the Logger.
Protected Attributes
array $_aServiceURLs = array()
Container for service URLs environments.
resource $_hSocket
SSL Socket.
ApnsPHP_Log_Interface $_logger
Logger.
integer $_nConnectRetryInterval
Connect retry interval in micro seconds.
integer $_nConnectRetryTimes = 3
Connect retry times.
integer $_nConnectTimeout
Connect timeout in seconds.
integer $_nEnvironment
Active environment.
integer $_nSocketSelectTimeout
Socket select timeout in micro seconds.
integer $_nWriteInterval
Write interval in micro seconds.
string $_sProviderCertificateFile
Provider certificate file with key (Bundled PEM).
string $_sProviderCertificatePassphrase
Provider certificate passphrase.
string $_sRootCertificationAuthorityFile
Root certification authority file.
Detailed Description
Abstract class: this is the superclass for all Apple Push Notification Service classes.
This class is responsible for the connection to the Apple Push Notification Service and Feedback.
See Also
http://tinyurl.com/ApplePushNotificationService
Definition at line 40 of file Abstract.php.
Constructor & Destructor Documentation
void __construct (integer $nEnvironment, string $sProviderCertificateFile)
Constructor.
Parameters
$nEnvironment Environment.
$sProviderCertificateFile Provider certificate file with key (Bundled PEM).
Exceptions
ApnsPHP_Exception if the environment is not sandbox or production or the provider certificate file is not readable.
Definition at line 79 of file Abstract.php.
     {
         if ($nEnvironment != self::ENVIRONMENT_PRODUCTION && $nEnvironment != self::ENVIRONMENT_SANDBOX) {
             throw new ApnsPHP_Exception(
                 "Invalid environment '{$nEnvironment}'"
             );
         }
         $this->_nEnvironment = $nEnvironment;
         if (!is_readable($sProviderCertificateFile)) {
             throw new ApnsPHP_Exception(
                 "Unable to read certificate file '{$sProviderCertificateFile}'"
             );
         }
         $this->_sProviderCertificateFile = $sProviderCertificateFile;
         $this->_nConnectTimeout = ini_get("default_socket_timeout");
         $this->_nWriteInterval = self::WRITE_INTERVAL;
         $this->_nConnectRetryInterval = self::CONNECT_RETRY_INTERVAL;
         $this->_nSocketSelectTimeout = self::SOCKET_SELECT_TIMEOUT;
     }
Member Function Documentation
boolean _connect () protected
Connects to Apple Push Notification service server.
Exceptions
ApnsPHP_Exception if is unable to connect.
Returns
True if successful connected.
See Also
http://php.net/manual/en/context.ssl.php
Definition at line 371 of file Abstract.php.
References $_nEnvironment, and _log().
Referenced by connect().
     {
         $sURL = $this->_aServiceURLs[$this->_nEnvironment];
         unset($aURLs);
         $this->_log("INFO: Trying {$sURL}...");
         /**
          * @see http://php.net/manual/en/context.ssl.php
          */
         $streamContext = stream_context_create(array('ssl' => array(
             'verify_peer' => isset($this->_sRootCertificationAuthorityFile),
             'cafile' => $this->_sRootCertificationAuthorityFile,
             'local_cert' => $this->_sProviderCertificateFile
         )));
         if (!empty($this->_sProviderCertificatePassphrase)) {
             stream_context_set_option($streamContext, 'ssl',
                 'passphrase', $this->_sProviderCertificatePassphrase);
         }
         $this->_hSocket = @stream_socket_client($sURL, $nError, $sError,
             $this->_nConnectTimeout, STREAM_CLIENT_CONNECT, $streamContext);
         if (!$this->_hSocket) {
             throw new ApnsPHP_Exception(
                 "Unable to connect to '{$sURL}': {$sError} ({$nError})"
             );
         }
         stream_set_blocking($this->_hSocket, 0);
         stream_set_write_buffer($this->_hSocket, 0);
         $this->_log("INFO: Connected to {$sURL}.");
         return true;
     }
void _log (string $sMessage) protected
Logs a message through the Logger.
Parameters
$sMessage The message.
Definition at line 414 of file Abstract.php.
Referenced by _connect(), ApnsPHP_Push_Server\_mainLoop(), ApnsPHP_Push\_updateQueue(), connect(), disconnect(), ApnsPHP_Push_Server\onShutdown(), ApnsPHP_Push_Server\onSignal(), ApnsPHP_Feedback\receive(), ApnsPHP_Push\send(), and ApnsPHP_Push_Server\start().
     {
         if (!isset($this->_logger)) {
             $this->_logger = new ApnsPHP_Log_Embedded();
         }
         $this->_logger->log($sMessage);
     }
void connect ()
Connects to Apple Push Notification service server.
Retries ConnectRetryTimes if unable to connect and waits setConnectRetryInterval between each attempts.
See Also
setConnectRetryTimes
setConnectRetryInterval
Exceptions
ApnsPHP_Exception if is unable to connect after ConnectRetryTimes.
Definition at line 328 of file Abstract.php.
References _connect(), and _log().
Referenced by ApnsPHP_Push\_updateQueue().
     {
         $bConnected = false;
         $nRetry = 0;
         while (!$bConnected) {
             try {
                 $bConnected = $this->_connect();
             } catch (ApnsPHP_Exception $e) {
                 $this->_log('ERROR: ' . $e->getMessage());
                 if ($nRetry >= $this->_nConnectRetryTimes) {
                     throw $e;
                 } else {
                     $this->_log(
                         "INFO: Retry to connect (" . ($nRetry+1) .
                         "/{$this->_nConnectRetryTimes})..."
                     );
                     usleep($this->_nConnectRetryInterval);
                 }
             }
             $nRetry++;
         }
     }
boolean disconnect ()
Disconnects from Apple Push Notifications service server.
Returns
True if successful disconnected.
Definition at line 356 of file Abstract.php.
References _log().
Referenced by ApnsPHP_Push\_updateQueue().
     {
         if (is_resource($this->_hSocket)) {
             $this->_log('INFO: Disconnected.');
             return fclose($this->_hSocket);
         }
         return false;
     }
string getCertificateAuthority ()
Get the Root Certification Authority file path.
Returns
Current Root Certification Authority file path.
Definition at line 185 of file Abstract.php.
References $_sRootCertificationAuthorityFile.
     {
         return $this->_sRootCertificationAuthorityFile;
     }
integer getConnectRetryInterval ()
Get the connect retry interval.
Returns
Connect retry interval in micro seconds.
Definition at line 280 of file Abstract.php.
References $_nConnectRetryInterval.
     {
         return $this->_nConnectRetryInterval;
     }
integer getConnectRetryTimes ()
Get the connect retry time value.
Returns
Connect retry times.
Definition at line 255 of file Abstract.php.
References $_nConnectRetryTimes.
     {
         return $this->_nConnectRetryTimes;
     }
integer getConnectTimeout ()
Get the connection timeout.
Returns
Connection timeout in seconds.
Definition at line 232 of file Abstract.php.
References $_nConnectTimeout.
     {
         return $this->_nConnectTimeout;
     }
ApnsPHP_Log_Interface getLogger ()
Get the Logger instance.
Returns
Current Logger instance.
Definition at line 139 of file Abstract.php.
References $_logger.
     {
         return $this->_logger;
     }
integer getSocketSelectTimeout ()
Get the TCP socket select timeout.
Returns
Socket select timeout in micro seconds.
Definition at line 312 of file Abstract.php.
References $_nSocketSelectTimeout.
     {
         return $this->_nSocketSelectTimeout;
     }
integer getWriteInterval ()
Get the write interval.
Returns
Write interval in micro seconds.
Definition at line 209 of file Abstract.php.
References $_nWriteInterval.
     {
         return $this->_nWriteInterval;
     }
void setConnectRetryInterval (integer $nRetryInterval)
Set the connect retry interval.
If the client is unable to connect to the server retries at least for ConnectRetryTimes and waits for this value between each attempts.
See Also
setConnectRetryTimes
Parameters
$nRetryInterval Connect retry interval in micro seconds.
Definition at line 270 of file Abstract.php.
     {
         $this->_nConnectRetryInterval = (int)$nRetryInterval;
     }
void setConnectRetryTimes (integer $nRetryTimes)
Set the connect retry times value.
If the client is unable to connect to the server retries at least for this value. The default connect retry times is 3.
Parameters
$nRetryTimes Connect retry times.
Definition at line 245 of file Abstract.php.
     {
         $this->_nConnectRetryTimes = (int)$nRetryTimes;
     }
void setConnectTimeout (integer $nTimeout)
Set the connection timeout.
The default connection timeout is the PHP internal value "default_socket_timeout".
See Also
http://php.net/manual/en/filesystem.configuration.php
Parameters
$nTimeout Connection timeout in seconds.
Definition at line 222 of file Abstract.php.
     {
         $this->_nConnectTimeout = (int)$nTimeout;
     }
void setLogger (ApnsPHP_Log_Interface $logger)
Set the Logger instance to use for logging purpose.
The default logger is ApnsPHP_Log_Embedded, an instance of ApnsPHP_Log_Interface that simply print to standard output log messages.
To set a custom logger you have to implement ApnsPHP_Log_Interface and use setLogger, otherwise standard logger will be used.
See Also
ApnsPHP_Log_Interface
ApnsPHP_Log_Embedded
Parameters
$logger Logger instance.
Exceptions
ApnsPHP_Exception if Logger is not an instance of ApnsPHP_Log_Interface.
Definition at line 118 of file Abstract.php.
     {
         if (!is_object($logger)) {
             throw new ApnsPHP_Exception(
                 "The logger should be an instance of 'ApnsPHP_Log_Interface'"
             );
         }
         if (!($logger instanceof ApnsPHP_Log_Interface)) {
             throw new ApnsPHP_Exception(
                 "Unable to use an instance of '" . get_class($logger) . "' as logger: " .
                 "a logger must implements ApnsPHP_Log_Interface."
             );
         }
         $this->_logger = $logger;
     }
void setProviderCertificatePassphrase (string $sProviderCertificatePassphrase)
Set the Provider Certificate passphrase.
Parameters
$sProviderCertificatePassphrase Provider Certificate passphrase.
Definition at line 150 of file Abstract.php.
     {
         $this->_sProviderCertificatePassphrase = $sProviderCertificatePassphrase;
     }
void setRootCertificationAuthority (string $sRootCertificationAuthorityFile)
Set the Root Certification Authority file.
Setting the Root Certification Authority file automatically set peer verification on connect.
See Also
http://tinyurl.com/GeneralProviderRequirements
http://www.entrust.net/
https://www.entrust.net/downloads/root_index.cfm
Parameters
$sRootCertificationAuthorityFile Root Certification Authority file.
Exceptions
ApnsPHP_Exception if Root Certification Authority file is not readable.
Definition at line 170 of file Abstract.php.
     {
         if (!is_readable($sRootCertificationAuthorityFile)) {
             throw new ApnsPHP_Exception(
                 "Unable to read Certificate Authority file '{$sRootCertificationAuthorityFile}'"
             );
         }
         $this->_sRootCertificationAuthorityFile = $sRootCertificationAuthorityFile;
     }
void setSocketSelectTimeout (integer $nSelectTimeout)
Set the TCP socket select timeout.
After writing to socket waits for at least this value for read stream to change status.
In Apple Push Notification protocol there isn't a real-time feedback about the correctness of notifications pushed to the server; so after each write to server waits at least SocketSelectTimeout. If, during this time, the read stream change its status and socket received an end-of-file from the server the notification pushed to server was broken, the server has closed the connection and the client needs to reconnect.
See Also
http://php.net/stream_select
Parameters
$nSelectTimeout Socket select timeout in micro seconds.
Definition at line 302 of file Abstract.php.
     {
         $this->_nSocketSelectTimeout = (int)$nSelectTimeout;
     }
void setWriteInterval (integer $nWriteInterval)
Set the write interval.
After each socket write operation we are sleeping for this time interval. To speed up the sending operations, use Zero as parameter but some messages may be lost.
Parameters
$nWriteInterval Write interval in micro seconds.
Definition at line 199 of file Abstract.php.
     {
         $this->_nWriteInterval = (int)$nWriteInterval;
     }
Field Documentation
array $_aServiceURLs = array() protected
Container for service URLs environments.
Definition at line 51 of file Abstract.php.
resource $_hSocket protected
SSL Socket.
Definition at line 68 of file Abstract.php.
ApnsPHP_Log_Interface $_logger protected
Logger.
Definition at line 66 of file Abstract.php.
Referenced by getLogger().
integer $_nConnectRetryInterval protected
Connect retry interval in micro seconds.
Definition at line 63 of file Abstract.php.
Referenced by getConnectRetryInterval().
integer $_nConnectRetryTimes = 3 protected
Connect retry times.
Definition at line 56 of file Abstract.php.
Referenced by getConnectRetryTimes().
integer $_nConnectTimeout protected
Connect timeout in seconds.
Definition at line 55 of file Abstract.php.
Referenced by getConnectTimeout().
integer $_nEnvironment protected
Active environment.
Definition at line 53 of file Abstract.php.
Referenced by _connect().
integer $_nSocketSelectTimeout protected
Socket select timeout in micro seconds.
Definition at line 64 of file Abstract.php.
Referenced by getSocketSelectTimeout().
integer $_nWriteInterval protected
Write interval in micro seconds.
Definition at line 62 of file Abstract.php.
Referenced by getWriteInterval().
string $_sProviderCertificateFile protected
Provider certificate file with key (Bundled PEM).
Definition at line 58 of file Abstract.php.
string $_sProviderCertificatePassphrase protected
Provider certificate passphrase.
Definition at line 59 of file Abstract.php.
string $_sRootCertificationAuthorityFile protected
Root certification authority file.
Definition at line 60 of file Abstract.php.
Referenced by getCertificateAuthority().
const CONNECT_RETRY_INTERVAL = 1000000
integer Default connect retry interval in micro seconds.
Definition at line 48 of file Abstract.php.
const DEVICE_BINARY_SIZE = 32
integer Device token length.
Definition at line 45 of file Abstract.php.
const ENVIRONMENT_PRODUCTION = 0
integer Production environment.
Definition at line 42 of file Abstract.php.
const ENVIRONMENT_SANDBOX = 1
integer Sandbox environment.
Definition at line 43 of file Abstract.php.
const SOCKET_SELECT_TIMEOUT = 1000000
integer Default socket select timeout in micro seconds.
Definition at line 49 of file Abstract.php.
const WRITE_INTERVAL = 10000
integer Default write interval in micro seconds.
Definition at line 47 of file Abstract.php.
The documentation for this class was generated from the following file:
Abstract.php