apns-php: ApnsPHP_Feedback Class Reference
ApnsPHP_Feedback Class Reference
Feedback
The Feedback Service client.
Public Member Functions
array receive ()
Receives feedback tuples from Apple Push Notification Service feedback.
Public Member Functions inherited from ApnsPHP_Abstract
void __construct (integer $nEnvironment, string $sProviderCertificateFile)
Constructor.
void connect ()
Connects to Apple Push Notification service server.
boolean disconnect ()
Disconnects from Apple Push Notifications service server.
string getCertificateAuthority ()
Get the Root Certification Authority file path.
integer getConnectRetryInterval ()
Get the connect retry interval.
integer getConnectRetryTimes ()
Get the connect retry time value.
integer getConnectTimeout ()
Get the connection timeout.
ApnsPHP_Log_Interface getLogger ()
Get the Logger instance.
integer getSocketSelectTimeout ()
Get the TCP socket select timeout.
integer getWriteInterval ()
Get the write interval.
void setConnectRetryInterval (integer $nRetryInterval)
Set the connect retry interval.
void setConnectRetryTimes (integer $nRetryTimes)
Set the connect retry times value.
void setConnectTimeout (integer $nTimeout)
Set the connection timeout.
void setLogger (ApnsPHP_Log_Interface $logger)
Set the Logger instance to use for logging purpose.
void setProviderCertificatePassphrase (string $sProviderCertificatePassphrase)
Set the Provider Certificate passphrase.
void setRootCertificationAuthority (string $sRootCertificationAuthorityFile)
Set the Root Certification Authority file.
void setSocketSelectTimeout (integer $nSelectTimeout)
Set the TCP socket select timeout.
void setWriteInterval (integer $nWriteInterval)
Set the write interval.
Data Fields
const TIME_BINARY_SIZE = 4
integer Timestamp binary size in bytes.
const TOKEN_LENGTH_BINARY_SIZE = 2
integer Token length binary size in bytes.
Data Fields inherited from ApnsPHP_Abstract
const CONNECT_RETRY_INTERVAL = 1000000
integer Default connect retry interval in micro seconds.
const DEVICE_BINARY_SIZE = 32
integer Device token length.
const ENVIRONMENT_PRODUCTION = 0
integer Production environment.
const ENVIRONMENT_SANDBOX = 1
integer Sandbox environment.
const SOCKET_SELECT_TIMEOUT = 1000000
integer Default socket select timeout in micro seconds.
const WRITE_INTERVAL = 10000
integer Default write interval in micro seconds.
Protected Member Functions
array _parseBinaryTuple (string $sBinaryTuple)
Parses binary tuples.
Protected Member Functions inherited from ApnsPHP_Abstract
boolean _connect ()
Connects to Apple Push Notification service server.
void _log (string $sMessage)
Logs a message through the Logger.
Protected Attributes
array $_aFeedback
Feedback container.
$_aServiceURLs
array Feedback URLs environments.
Protected Attributes inherited from ApnsPHP_Abstract
array $_aServiceURLs = array()
Container for service URLs environments.
resource $_hSocket
SSL Socket.
ApnsPHP_Log_Interface $_logger
Logger.
integer $_nConnectRetryInterval
Connect retry interval in micro seconds.
integer $_nConnectRetryTimes = 3
Connect retry times.
integer $_nConnectTimeout
Connect timeout in seconds.
integer $_nEnvironment
Active environment.
integer $_nSocketSelectTimeout
Socket select timeout in micro seconds.
integer $_nWriteInterval
Write interval in micro seconds.
string $_sProviderCertificateFile
Provider certificate file with key (Bundled PEM).
string $_sProviderCertificatePassphrase
Provider certificate passphrase.
string $_sRootCertificationAuthorityFile
Root certification authority file.
Detailed Description
The Feedback Service client.
Apple Push Notification Service includes a feedback service that APNs continually updates with a per-application list of devices for which there were failed-delivery attempts. Providers should periodically query the feedback service to get the list of device tokens for their applications, each of which is identified by its topic. Then, after verifying that the application hasn’t recently been re-registered on the identified devices, a provider should stop sending notifications to these devices.
See Also
http://tinyurl.com/ApplePushNotificationFeedback
Definition at line 39 of file Feedback.php.
Member Function Documentation
array _parseBinaryTuple (string $sBinaryTuple) protected
Parses binary tuples.
Parameters
$sBinaryTuple A binary tuple to parse.
Returns
Array with timestamp, tokenLength and deviceToken keys.
Definition at line 113 of file Feedback.php.
Referenced by receive().
     {
         return unpack('Ntimestamp/ntokenLength/H*deviceToken', $sBinaryTuple);
     }
array receive ()
Receives feedback tuples from Apple Push Notification Service feedback.
Every tuple (array) contains:
timestamp indicating when the APNs determined that the application no longer exists on the device. This value represents the seconds since 1970, anchored to UTC. You should use the timestamp to determine if the application on the device re-registered with your service since the moment the device token was recorded on the feedback service. If it hasn’t, you should cease sending push notifications to the device.
tokenLength The length of the device token (usually 32 bytes).
deviceToken The device token.
Returns
Array of feedback tuples (array).
Definition at line 66 of file Feedback.php.
References $_aFeedback, ApnsPHP_Abstract\_log(), and _parseBinaryTuple().
     {
         $nFeedbackTupleLen = self::TIME_BINARY_SIZE + self::TOKEN_LENGTH_BINARY_SIZE + self::DEVICE_BINARY_SIZE;
         $this->_aFeedback = array();
         $sBuffer = '';
         while (!feof($this->_hSocket)) {
             $this->_log('INFO: Reading...');
             $sBuffer .= $sCurrBuffer = fread($this->_hSocket, 8192);
             $nCurrBufferLen = strlen($sCurrBuffer);
             if ($nCurrBufferLen > 0) {
                 $this->_log("INFO: {$nCurrBufferLen} bytes read.");
             }
             unset($sCurrBuffer, $nCurrBufferLen);
             $nBufferLen = strlen($sBuffer);
             if ($nBufferLen >= $nFeedbackTupleLen) {
                 $nFeedbackTuples = floor($nBufferLen / $nFeedbackTupleLen);
                 for ($i = 0; $i < $nFeedbackTuples; $i++) {
                     $sFeedbackTuple = substr($sBuffer, 0, $nFeedbackTupleLen);
                     $sBuffer = substr($sBuffer, $nFeedbackTupleLen);
                     $this->_aFeedback[] = $aFeedback = $this->_parseBinaryTuple($sFeedbackTuple);
                     $this->_log(sprintf("INFO: New feedback tuple: timestamp=%d (%s), tokenLength=%d, deviceToken=%s.",
                         $aFeedback['timestamp'], date('Y-m-d H:i:s', $aFeedback['timestamp']),
                         $aFeedback['tokenLength'], $aFeedback['deviceToken']
                     ));
                     unset($aFeedback);
                 }
             }
             $read = array($this->_hSocket);
             $null = NULL;
             $nChangedStreams = stream_select($read, $null, $null, 0, $this->_nSocketSelectTimeout);
             if ($nChangedStreams === false) {
                 $this->_log('WARNING: Unable to wait for a stream availability.');
                 break;
             }
         }
         return $this->_aFeedback;
     }
Field Documentation
array $_aFeedback protected
Feedback container.
Definition at line 49 of file Feedback.php.
Referenced by receive().
$_aServiceURLs protected
Initial value:
= array(
        'tls://feedback.push.apple.com:2196',
        'tls://feedback.sandbox.push.apple.com:2196'
    )
array Feedback URLs environments.
Definition at line 44 of file Feedback.php.
const TIME_BINARY_SIZE = 4
integer Timestamp binary size in bytes.
Definition at line 41 of file Feedback.php.
const TOKEN_LENGTH_BINARY_SIZE = 2
integer Token length binary size in bytes.
Definition at line 42 of file Feedback.php.
The documentation for this class was generated from the following file:
Feedback.php